version: '3.7'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=couriertest
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=couriertest
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bigdan110702@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123123
    ports:
      - "5050:80"