spring:
  main:
    banner-mode: off

  datasource:
      url: jdbc:postgresql://localhost/couriertest
      username: couriertest
      password: 123123

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    show-sql: true